# Generated by Django 4.2.7 on 2025-03-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepacompglobal',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
