# Generated by Django 4.2.7 on 2025-03-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom du partenaire'),
        ),
    ]
