# Generated by Django 4.2.7 on 2025-03-11 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0002_alter_partenaire_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['-date_fin']},
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rapport',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rap_app.centre'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='derniers_commentaires',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rapport',
            name='entrees_formation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rapport',
            name='nombre_partenaires',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rapport',
            name='prevus_crif',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rapport',
            name='prevus_mp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rapport',
            name='saturation_moyenne',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapport',
            name='saturation_par_formation',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rapport',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rap_app.statut'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='type_offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rap_app.typeoffre'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='rap_app.formation'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='inscrits_crif',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='inscrits_mp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='nombre_candidats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='nombre_entretiens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='nombre_evenements',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='periode',
            field=models.CharField(choices=[('Hebdomadaire', 'Hebdomadaire'), ('Mensuel', 'Mensuel'), ('Annuel', 'Annuel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='total_inscrits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='total_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['centre'], name='rap_app_rap_centre__cf0208_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['type_offre'], name='rap_app_rap_type_of_e4b013_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['statut'], name='rap_app_rap_statut__098b07_idx'),
        ),
    ]
