# Generated by Django 4.2.7 on 2025-03-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0002_prepacompglobal_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepacompglobal',
            name='total',
        ),
    ]
