# Generated by Django 4.2.7 on 2025-03-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0003_alter_rapport_options_remove_rapport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rap_app_rap_date_de_392072_idx',
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rap_app_rap_date_fi_a3dd0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rap_app_rap_periode_db57b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rap_app_rap_centre__cf0208_idx',
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rap_app_rap_type_of_e4b013_idx',
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rap_app_rap_statut__098b07_idx',
        ),
        migrations.AlterField(
            model_name='rapport',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='rap_app.formation'),
        ),
    ]
