# Generated by Django 4.2.7 on 2025-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0003_remove_prepacompglobal_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepacompglobal',
            name='adhesions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
