# Generated by Django 4.2.7 on 2025-03-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0004_prepacompglobal_adhesions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepacompglobal',
            options={'verbose_name': 'Bilan global PrépaComp', 'verbose_name_plural': 'Bilans globaux PrépaComp'},
        ),
        migrations.AlterModelOptions(
            name='semaine',
            options={'ordering': ['-date_debut_semaine'], 'verbose_name': 'Semaine', 'verbose_name_plural': 'Semaines'},
        ),
        migrations.RenameField(
            model_name='semaine',
            old_name='date_debut',
            new_name='date_debut_semaine',
        ),
        migrations.RenameField(
            model_name='semaine',
            old_name='date_fin',
            new_name='date_fin_semaine',
        ),
        migrations.RenameField(
            model_name='semaine',
            old_name='nombre_candidats',
            new_name='nombre_presents_ic',
        ),
        migrations.RenameField(
            model_name='semaine',
            old_name='nombre_presents',
            new_name='objectif_annuel_prepa',
        ),
        migrations.AlterUniqueTogether(
            name='prepacompglobal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='centre',
            name='objectif_hebdomadaire_prepa',
        ),
        migrations.AddField(
            model_name='semaine',
            name='nombre_par_atelier',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='semaine',
            name='objectif_mensuel_prepa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prepacompglobal',
            name='centre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rap_app.centre'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='prepacompglobal',
            unique_together={('centre', 'annee')},
        ),
    ]
