# Generated by Django 4.2.7 on 2025-03-12 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0004_alter_rapport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['-date_fin'], 'verbose_name': 'Rapport de formation', 'verbose_name_plural': 'Rapports de formation'},
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='derniers_commentaires',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='entrees_formation',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='nombre_partenaires',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='prevus_crif',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='prevus_mp',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='saturation_moyenne',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='saturation_par_formation',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='type_offre',
        ),
        migrations.AddField(
            model_name='rapport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début de la période'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin de la période'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='rap_app.formation', verbose_name='Formation associée'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='inscrits_crif',
            field=models.PositiveIntegerField(default=0, verbose_name='Inscrits CRIF'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='inscrits_mp',
            field=models.PositiveIntegerField(default=0, verbose_name='Inscrits MP'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='nombre_candidats',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de candidats'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='nombre_entretiens',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'entretiens"),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='nombre_evenements',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'événements"),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='periode',
            field=models.CharField(choices=[('Hebdomadaire', 'Hebdomadaire'), ('Mensuel', 'Mensuel'), ('Annuel', 'Annuel')], max_length=50, verbose_name='Période du rapport'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='total_inscrits',
            field=models.PositiveIntegerField(default=0, verbose_name='Total des inscrits'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='total_places',
            field=models.PositiveIntegerField(default=0, verbose_name='Total des places'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['date_debut'], name='rap_app_rap_date_de_392072_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['date_fin'], name='rap_app_rap_date_fi_a3dd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['periode'], name='rap_app_rap_periode_db57b2_idx'),
        ),
    ]
