# Generated by Django 4.2.7 on 2025-03-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0005_alter_rapport_options_remove_rapport_centre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
