# Generated by Django 4.2.7 on 2025-03-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0005_alter_prepacompglobal_options_alter_semaine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepacompglobal',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rap_app.centre'),
        ),
    ]
