# Generated by Django 4.2.7 on 2025-03-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0006_alter_prepacompglobal_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='objectif_hebdomadaire_prepa',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
