# Generated by Django 4.2.7 on 2025-03-29 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0007_centre_objectif_hebdomadaire_prepa'),
    ]

    operations = [
        migrations.CreateModel(
            name='VAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('date_creation', models.DateField(help_text="Date à laquelle la VAE a été créée, pas nécessairement aujourd'hui", verbose_name='Date de création')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie dans le système')),
                ('statut', models.CharField(choices=[('info', "Demande d'informations"), ('dossier', 'Dossier en cours'), ('attente_financement', 'En attente de financement'), ('accompagnement', 'Accompagnement en cours'), ('jury', 'En attente de jury'), ('terminee', 'VAE terminée'), ('abandonnee', 'VAE abandonnée')], default='info', max_length=20, verbose_name='Statut')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaes', to='rap_app.centre', verbose_name='Centre')),
            ],
            options={
                'verbose_name': 'VAE',
                'verbose_name_plural': 'VAEs',
                'ordering': ['-date_creation', 'centre'],
            },
        ),
        migrations.CreateModel(
            name='SuiviJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('objectif_jury', models.PositiveIntegerField(default=0, verbose_name='Objectif jury')),
                ('jurys_realises', models.PositiveIntegerField(default=0, verbose_name='Jurys réalisés')),
                ('pourcentage_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6, verbose_name='Pourcentage mensuel')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap_app.centre', verbose_name='Centre')),
            ],
            options={
                'verbose_name': 'Suivi des jurys',
                'verbose_name_plural': 'Suivis des jurys',
                'ordering': ['annee', 'mois', 'centre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutVAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('info', "Demande d'informations"), ('dossier', 'Dossier en cours'), ('attente_financement', 'En attente de financement'), ('accompagnement', 'Accompagnement en cours'), ('jury', 'En attente de jury'), ('terminee', 'VAE terminée'), ('abandonnee', 'VAE abandonnée')], max_length=20, verbose_name='Statut')),
                ('date_changement_effectif', models.DateField(help_text="Date à laquelle le changement de statut a eu lieu (pas nécessairement aujourd'hui)", verbose_name='Date effective du changement')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie dans le système')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('vae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='rap_app.vae', verbose_name='VAE')),
            ],
            options={
                'verbose_name': 'Historique de statut VAE',
                'verbose_name_plural': 'Historiques de statuts VAE',
                'ordering': ['-date_changement_effectif', '-date_saisie'],
            },
        ),
        migrations.AddIndex(
            model_name='vae',
            index=models.Index(fields=['centre', 'statut'], name='rap_app_vae_centre__309bad_idx'),
        ),
        migrations.AddIndex(
            model_name='vae',
            index=models.Index(fields=['date_creation'], name='rap_app_vae_date_cr_61a6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='suivijury',
            index=models.Index(fields=['centre', 'annee', 'mois'], name='rap_app_sui_centre__1773ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suivijury',
            unique_together={('centre', 'annee', 'mois')},
        ),
    ]
