# Generated by Django 4.2.7 on 2025-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0008_vae_suivijury_historiquestatutvae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='objectif_annuel_jury',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centre',
            name='objectif_mensuel_jury',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
