# Generated by Django 4.2.7 on 2025-03-19 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0008_company_prospection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email du contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Métier du contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Entrez un numéro de téléphone français valide commençant par 01, 02, ..., 06 ou 07.', regex='^(0[1-9]\\d{8})$|^(?:\\+33|0033)[1-9]\\d{8}$')], verbose_name='Numéro de téléphone du contact'),
        ),
    ]
