# Generated by Django 4.2.7 on 2025-03-21 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rap_app', '0009_remove_company_email_remove_company_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueProspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('ancien_statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], max_length=20)),
                ('nouveau_statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('prochain_contact', models.DateField(blank=True, null=True, verbose_name='Date de relance')),
                ('resultat', models.TextField(blank=True, null=True, verbose_name='Résultat ou retour de la prospection')),
                ('moyen_contact', models.CharField(blank=True, choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('visite', 'Visite'), ('réseaux', 'Réseaux sociaux')], max_length=50, null=True, verbose_name='Moyen de contact')),
            ],
            options={
                'verbose_name': 'Historique de prospection',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AlterModelOptions(
            name='historiqueformation',
            options={'ordering': ['-date_modification'], 'verbose_name': 'Historique de modification de formation'},
        ),
        migrations.AlterModelOptions(
            name='prospection',
            options={'ordering': ['-date_prospection'], 'verbose_name': 'Suivi de la prospection', 'verbose_name_plural': 'Suivis des prospections'},
        ),
        migrations.RemoveIndex(
            model_name='historiqueformation',
            name='rap_app_his_created_c1d4f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueformation',
            name='rap_app_his_action_40c15f_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueformation',
            name='rap_app_his_formati_aa2815_idx',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='action',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='ancien_statut',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='details',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='inscrits_crif',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='inscrits_mp',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='inscrits_total',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='nouveau_statut',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='saturation',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='semaine',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='taux_remplissage',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='total_places',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historiqueformation',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='ancienne_valeur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='champ_modifie',
            field=models.CharField(default='non_specifié', max_length=100, verbose_name='Champ modifié'),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire lié à la modification'),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='nouvelle_valeur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospection',
            name='motif',
            field=models.CharField(choices=[('POEI', 'POEI'), ('Apprentissage', 'Apprentissage'), ('VAE', 'VAE'), ('partenariat', 'Établir un partenariat'), ('autre', 'Autre')], default='prise_contact', max_length=30, verbose_name='Motif de la prospection'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='rap_app.formation'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires de la prospection'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospections', to='rap_app.formation', verbose_name='Formation en lien'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='objectif',
            field=models.CharField(choices=[('prise_contact', 'Prise de contact'), ('rendez_vous', 'Obtenir un rendez-vous'), ('presentation_offre', 'Présentation d’une offre'), ('contrat', 'Signer un contrat'), ('partenariat', 'Établir un partenariat'), ('autre', 'Autre')], default='prise_contact', max_length=30, verbose_name='Objectif de la prospection'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la prospection'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='a_faire', max_length=20, verbose_name='Statut de la prospection'),
        ),
        migrations.AddField(
            model_name='historiqueprospection',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiqueprospection',
            name='prospection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='rap_app.prospection'),
        ),
    ]
