# Generated by Django 4.2.7 on 2025-03-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rap_app', '0010_historiqueprospection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueformation',
            name='action',
            field=models.CharField(default='modification', max_length=100),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='ancien_statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('Non renséigné', 'Non renséigné')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='nouveau_statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('Non renséigné', 'Non renséigné')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('Non renséigné', 'Non renséigné')], default='a_faire', max_length=20, verbose_name='Statut de la prospection'),
        ),
    ]
