# Generated by Django 4.2.7 on 2025-03-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0011_historiqueformation_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoffre',
            name='couleur',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Couleur associée (hexadécimal)'),
        ),
    ]
