# Generated by Django 4.2.7 on 2025-03-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0013_alter_company_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recherche',
        ),
    ]
