# Generated by Django 4.2.7 on 2025-03-23 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rap_app', '0014_delete_recherche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueformation',
            options={'ordering': ['-date_modification'], 'verbose_name': 'Historique de modification de formation'},
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='rap_app_for_statut__266c03_idx',
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='rap_app_for_centre__02fbd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='rap_app_for_statut__25de1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='rap_app_for_centre__5e5c3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueformation',
            name='rap_app_his_formati_aa2815_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueformation',
            name='rap_app_his_date_mo_a927c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueformation',
            name='rap_app_his_modifie_241c9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueformation',
            name='rap_app_his_champ_m_84201a_idx',
        ),
        migrations.AlterField(
            model_name='formation',
            name='assistante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assistante'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='cap',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité maximale'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='rap_app.centre', verbose_name='Centre de formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='convocation_envoie',
            field=models.BooleanField(default=False, verbose_name='Convocation envoyée'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='dernier_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Dernier commentaire'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='entresformation',
            field=models.PositiveIntegerField(default=0, verbose_name='Entrées en formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='inscrits_crif',
            field=models.PositiveIntegerField(default=0, verbose_name='Inscrits CRIF'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='inscrits_mp',
            field=models.PositiveIntegerField(default=0, verbose_name='Inscrits MP'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom de la formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nombre_candidats',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de candidats'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nombre_entretiens',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'entretiens"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nombre_evenements',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'événements"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='num_kairos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro Kairos'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='num_offre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro de l'offre"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='num_produit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro du produit'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='partenaires',
            field=models.ManyToManyField(blank=True, related_name='formations', to='rap_app.partenaire', verbose_name='Partenaires'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prevus_crif',
            field=models.PositiveIntegerField(default=0, verbose_name='Places prévues CRIF'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prevus_mp',
            field=models.PositiveIntegerField(default=0, verbose_name='Places prévues MP'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='rap_app.statut', verbose_name='Statut de la formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='type_offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='rap_app.typeoffre', verbose_name="Type d'offre"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='action',
            field=models.CharField(default='modification', max_length=100),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='ancienne_valeur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='champ_modifie',
            field=models.CharField(default='non_specifié', max_length=100, verbose_name='Champ modifié'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire lié à la modification'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='rap_app.formation'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='nouvelle_valeur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
