# Generated by Django 4.2.7 on 2025-03-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0015_alter_historiqueformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('a_adhere', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectifAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('objectif', models.IntegerField(default=430)),
            ],
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('numero_semaine', models.PositiveIntegerField()),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('objectif_annuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap_app.objectifannuel')),
            ],
            options={
                'ordering': ['-date_debut'],
                'unique_together': {('numero_semaine', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rap_app.candidat')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap_app.departement')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap_app.semaine')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap_app.departement'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap_app.semaine'),
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('objectif_annuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap_app.objectifannuel')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
